"""Export the authored bilingual website accounts and editorial coverage ledger.

Run from the repository root: python3 scripts/accounts/build_website_accounts.py Edit the TSV
drafts; CSV and Markdown outputs are regenerated by this script.
"""

import csv
import hashlib
import json
from collections import defaultdict
from pathlib import Path

root = Path(__file__).resolve().parents[2]
folder = root / "content/accounts"  # authored TSVs
review = folder / "review"  # ledgers, CSV exports, manifest, source snapshots
reading = folder / "reading"  # Markdown reading copies

# Read the maintained sources and authored drafts.
with (root / "data/count/dataset/report_text.csv").open(encoding="utf-8-sig") as handle:
    annual_source = list(csv.DictReader(handle))
with (root / "data/count/dataset/paper_text.csv").open(encoding="utf-8-sig") as handle:
    paper_source = list(csv.DictReader(handle))
with (folder / "year-accounts.tsv").open(encoding="utf-8-sig") as handle:
    annual_drafts = list(csv.DictReader(handle, delimiter="\t"))
with (folder / "species-sections.tsv").open(encoding="utf-8-sig") as handle:
    sections = list(csv.DictReader(handle, delimiter="\t"))
with (review / "reference/source_taxa.csv").open(encoding="utf-8-sig") as handle:
    names_fr = {
        r["avibase_id"]: r["taxon_name_original"]
        for r in csv.DictReader(handle)
        if r["source"] == "historical"
    }
with (root / "data/count/dataset/taxonomy.csv").open(encoding="utf-8-sig") as handle:
    taxa = {r["taxon_id"]: r for r in csv.DictReader(handle)}

names_fr.update(
    {
        "avibase-93CA037F": "Goéland pontique",
        "avibase-9EA1F12D": "Faucon d’Éléonore",
        "avibase-CC65921F": "Buse féroce",
        "avibase-E826E9F3": "Goéland marin",
        "avibase-FA2F9125": "Huppe fasciée",
    }
)
# This paper-only taxon is resolved in the local Clements 2025 reference checklist.
taxa["avibase-FA2F9125"] = {
    "english_name": "Common Hoopoe",
    "scientific_name": "Upupa epops",
    "taxon_rank": "species",
}

annual_species = [r for r in annual_source if r["category"] == "species"]
source_pairs = {(r["year"], r["key"]) for r in annual_species}
drafts = {(r["year"], r["key"]): r for r in annual_drafts}
keys = {r["key"] for r in annual_species + paper_source if r["category"] == "species"}
assert len(drafts) == len(annual_drafts)
assert len(source_pairs) == len(annual_species)
assert drafts.keys() <= source_pairs
assert len({(r["key"], r["section"]) for r in sections}) == len(sections)
assert all(
    r["key"] in keys and r["section"] in ("passage", "evolution", "particularites")
    for r in sections
)
assert all(
    r["text_fr"].strip() and r["text_en"].strip() and None not in r
    for r in annual_drafts + sections
)

section_text = defaultdict(dict)
for row in sections:
    for language in ("fr", "en"):
        section_text[row["key"]][f'{row["section"]}_{language}'] = row[f"text_{language}"]

# Keep source references outside website prose, including shared-species inputs.
related = {
    "avibase-C2565B65": ["group-aigle-pomarin-criard"],
    "avibase-BAC4CA22": ["group-aigle-pomarin-criard"],
    "avibase-2A16982E": ["group-aigle-pomarin-criard"],
    "avibase-1078FFEA": ["group-corbeau-freux-choucas-des-tours"],
    "avibase-D4C32F8E": ["group-corbeau-freux-choucas-des-tours"],
    "avibase-58C502EA": ["group-hirondelles-rustique-fenetre-rivage"],
    "avibase-30FEC6BE": ["group-hirondelles-rustique-fenetre-rivage"],
    "avibase-94A1C447": ["group-hirondelles-rustique-fenetre-rivage"],
    "avibase-F837F893": ["avibase-760F307A", "avibase-68E4C0D1"],
    "avibase-55CCEE2D": ["avibase-30FEC6BE", "avibase-58C502EA", "avibase-94A1C447"],
    "avibase-6364E4A5": ["group-hirondelles-rustique-fenetre-rivage"],
}
coverage = []
species_accounts = []
section_fields = [
    f"{section}_{language}"
    for section in ("passage", "evolution", "particularites")
    for language in ("fr", "en")
]
for key in sorted(keys, key=lambda k: names_fr.get(k, k)):
    contributing_keys = {key, *related.get(key, [])}
    inputs = [
        f'paper:{r["source_id"]}:species:{r["key"]}'
        for r in paper_source
        if r["key"] in contributing_keys
    ]
    inputs += [
        f'annual:{r["year"]}:species:{r["key"]}'
        for r in annual_species
        if r["key"] in contributing_keys
    ]
    populated = bool(section_text[key])
    coverage.append(
        dict(
            account="general",
            year="",
            key=key,
            status="draft" if populated else "no_general_narrative",
            source_rows=";".join(inputs),
            context_rows="",
            note="Shared source grouping retained for provenance, not a species account."
            if key.startswith("group-")
            else ""
            if populated
            else "Source contains isolated sightings or numerical details; no general prose added.",
        )
    )
    if key.startswith("group-"):
        continue
    taxon = taxa[key]
    species_accounts.append(
        dict(
            key=key,
            name_fr=names_fr[key],
            name_en=taxon["english_name"],
            scientific_name=taxon["scientific_name"],
            taxon_rank=taxon["taxon_rank"],
            **{field: section_text[key].get(field, "") for field in section_fields},
            status="draft" if populated else "no_general_narrative",
        )
    )

annual_accounts = []
for row in sorted(annual_species, key=lambda r: (r["year"], names_fr[r["key"]])):
    key = row["key"]
    draft = drafts.get((row["year"], key), {})
    status = "draft" if draft else "numerical_or_list_only"
    annual_accounts.append(
        dict(
            year=row["year"],
            key=key,
            name_fr=names_fr[key],
            name_en=taxa[key]["english_name"],
            text_fr=draft.get("text_fr", ""),
            text_en=draft.get("text_en", ""),
            status=status,
        )
    )
    coverage.append(
        dict(
            account="annual",
            year=row["year"],
            key=key,
            status=status,
            source_rows=f'annual:{row["year"]}:species:{key}',
            context_rows=";".join(
                f'annual:{r["year"]}:{r["category"]}:{r["key"]}'
                for r in annual_source
                if r["year"] == row["year"]
                and r["category"] in ("monitoring", "weather", "results")
            ),
            note=""
            if draft
            else "Only counts, dates or a short age/sex list; leave narrative empty.",
        )
    )

# Export UTF-8 CSV files and paired reading copies.
exports = [
    ("species-accounts.csv", species_accounts),
    ("species-year-accounts.csv", annual_accounts),
    ("coverage.csv", coverage),
]
for name, rows in exports:
    with (review / name).open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

labels = {
    "fr": {
        "title": "Comptes par espèce",
        "annual": "Comptes annuels",
        "passage": "Passage au Défilé",
        "evolution": "Évolution du passage",
        "particularites": "Particularités",
    },
    "en": {
        "title": "Species accounts",
        "annual": "Annual accounts",
        "passage": "Passage at the Défilé",
        "evolution": "Changes in passage",
        "particularites": "Distinctive observations",
    },
}
for language in ("fr", "en"):
    general = [
        f'# {labels[language]["title"]}',
        "",
        "Version de travail bilingue · 9 octobre 2026."
        if language == "fr"
        else "Bilingual working draft · 9 October 2026.",
    ]
    yearly = [
        f'# {labels[language]["annual"]}',
        "",
        "Version de travail bilingue · 9 octobre 2026."
        if language == "fr"
        else "Bilingual working draft · 9 October 2026.",
    ]
    for row in species_accounts:
        if row["status"] != "draft":
            continue
        general += ["", f'## {row[f"name_{language}"]}', ""]
        for section in ("passage", "evolution", "particularites"):
            if row[f"{section}_{language}"]:
                general += [
                    f"### {labels[language][section]}",
                    "",
                    row[f"{section}_{language}"],
                    "",
                ]
    for row in annual_accounts:
        if row["status"] == "draft":
            yearly += [
                "",
                f'## {row[f"name_{language}"]} · {row["year"]}',
                "",
                row[f"text_{language}"],
            ]
    (reading / f"species-{language}.md").write_text(
        "\n".join(general).replace("\n\n\n", "\n\n").rstrip() + "\n"
    )
    (reading / f"years-{language}.md").write_text("\n".join(yearly).rstrip() + "\n")

paths = [
    "data/count/dataset/report_text.csv",
    "data/count/dataset/paper_text.csv",
    "content/accounts/review/reference/annual-totals.csv",
    "content/accounts/review/reference/source_taxa.csv",
    "data/count/dataset/taxonomy.csv",
    "data/count/dataset/count.csv",
    "data/count/dataset/survey.csv",
    "content/accounts/year-accounts.tsv",
    "content/accounts/species-sections.tsv",
]
manifest = dict(
    prepared="2026-10-09",
    editorial_language="fr",
    languages=["fr", "en"],
    species_with_prose=sum(r["status"] == "draft" for r in species_accounts),
    annual_with_prose=len(annual_drafts),
    annual_without_prose=len(annual_species) - len(annual_drafts),
    annual_source_years=sorted({r["year"] for r in annual_species}),
    source_sha256={p: hashlib.sha256((root / p).read_bytes()).hexdigest() for p in paths},
)
(review / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
print(
    f'Exported {manifest["species_with_prose"]} general accounts and {manifest["annual_with_prose"]} annual accounts in French and English; {manifest["annual_without_prose"]} annual narratives intentionally empty.'
)
